version: '3.1'
services:
  jenkins:
    build: ./jenkins-master/
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_USER=admin
      - JENKINS_PASS=admin
      - JENKINS_EMAIL=email
      - JENKINS_URL=http://jenkins.vitaltax.uk
      - JENKINS_EXECUTORS_NUM=5

volumes:
  jenkins_home:
